### ISSUE TITLE
Issue with bcm2835 module

### ISSUE THREAD

**Issue by renderit** [ul-gh/PiPyADC#2]
Hi, on checking/working with the [High-Precision AD/DA Board](http://www.waveshare.com/wiki/High-Precision_AD/DA_Board) on a raspberry pi 3. When I run the example.py, I'm getting the  following error:

```
PiPyADC: Example file for class ADS1256 in module pipyadc:

ADS1256 cycling through eight input channels.

Hardware: Waveshare ADS1256 board interfaced to the Raspberry Pi 3

Ulrich Lukas 2017-03-10


Press CTRL-C to exit.
Unable to determine hardware version. I see: Hardware	: BCM2835
,
 - expecting BCM2708 or BCM2709.
If this is a genuine Raspberry Pi then please report this
to projects@drogon.net. If this is not a Raspberry Pi then you
are on your own as wiringPi is designed to support the
Raspberry Pi ONLY.
```

**Comment by ul-gh** [comment]
Hi, this is an incompatibility with the latest kernel upgrade and the wiringpi library.

This works for me:
sudo rpi-update 52241088c1da59a359110d39c1875cda56496764

From: https://www.domoticz.com/forum/viewtopic.php?t=16852

Do not forget to upgrade the wiringpi python library if you upgrade other parts of the system:
sudo pip install -U wiringpi

In a few days, I guess they will fix the issue with the latest Linux kernel for the raspi and wiringpi.
I will maybe look into it in a few days.

Please let me know if this helped!
